name: Jose Pereira
author: Jose Pereira
baseurl: /
description: theme for jekyll
github: http://www.github.com/jpereiran
facebook: https://www.facebook.com/planetarypiedpiper
linkedin: https://www.linkedin.com/in/jose-pereira-b9910815b/
email: jpereira[at]pucp.edu.pe
location: 12°4'38"S   77°5'34"W
disqus: 

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
